version: '3.8'

services:
  rss_bot:
    build:
      context: .
    container_name: rss_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./sent_data:/app  # 用于保存已发送记录 sent_items.json